---@meta
--- doprog.zones.stratos — Stratos: Zephyr's Flight (TBL entry zone).
--- Annotation-only marker. Quest files in this folder return doprog.Quest /
--- doprog.Mission instances; index.lua aggregates them in progression order.
---
--- Giver NPCs (confirmed via tbl.eqresource.com Quests-by-NPC):
---   Grieving Soul Scent     -> Soldier of Air, Fight Fire (mission)
---   Ashen Wandering Horizon -> Do Unto Them
---   Iron Lightning Spirit   -> Earning One's Place, A Petitioner's Plight
---   Dusky Iron Meditation   -> Key to the Kingdom
---   Rianar Gadliun          -> Political Awareness
return {}
